[package]

name         = "proteus"
version      = "1.0.0"
authors      = ["Wire Swiss GmbH <support@wire.com>"]
description  = "Axolotl protocol implementation"
homepage     = "https://github.com/wireapp/proteus"
repository   = "git@github.com:wireapp/proteus.git"
license      = "GPL-3.0"

[dependencies]
byteorder     = ">  0.2.0"
cbor-codec    = ">= 0.7.0"
hkdf          = { git = "https://github.com/wireapp/hkdf", tag = "v0.2.0" }
libc          = ">  0.1.0"
sodiumoxide   = { version = ">= 0.0.12", default-features = false }

